# Copyright Verizon Media. All rights reserved.

# Site settings
title: Vespa Cloud
email: ""
description: ""
baseurl: ""
url: ""
defaults:
    -
        scope:
            path: ""
        values:
            layout: "default"
            index: true

search:
    namespace: "cloud"
    do_feed  : true
    do_index_removal_before_feed: false
    feed_endpoints:
        - url: https://vespacloud-docsearch.vespa-team.aws-us-east-1c.z.vespa-app.cloud/
          indexes:
              - cloud_index.json
        - url: https://vespacloud-docsearch.vespa-team.aws-ap-northeast-1a.z.vespa-app.cloud/
          indexes:
              - cloud_index.json              

# Build settings
markdown: kramdown

exclude: # avoid regenerating loop
    - Gemfile
    - Gemfile.lock
    - node_modules
    - vendor/bundle/
    - vendor/cache/
    - vendor/gems/
    - vendor/ruby/
    - cloud_index.json
    - .idea
    - test

plugins:
    - jekyll-redirect-from
