shared:
  settings:
    email:
      addresses: [kraune@verizonmedia.com]
      statuses: [SUCCESS, FAILURE]

jobs:
  link-checker-cloud:
    requires: [~pr, ~commit]
    image: ruby:2.6
    environment:
      USER_SHELL_BIN: bash
    annotations:
      screwdriver.cd/buildPeriodically: H 0 * * *
    steps:
      - install-deps: |
          gem install bundler
      - check-links: |
          export LANG=C.UTF-8
          bundle install
          bundle exec jekyll build
          bundle exec htmlproofer --assume-extension --empty_alt_ignore ./_site
